version: '3.9'

services:
  api:
    build: ./server
    container_name: be_apply_digital
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  db_data:
